[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["agora-token"]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_TOKEN_SERVER_URL = "/.netlify/functions"