export const VOICE_CONSTANTS = {
  // Volume thresholds (0-1)
  SPEAKING_THRESHOLD: 0.2,
  SPEAKING_HOLD_THRESHOLD: 0.15,
  VOLUME_SMOOTHING: 0.3,

  // Timing constants (ms)
  SPEAKING_TIMEOUT: 200,
  UPDATE_DEBOUNCE: 50,
  RECOVERY_DELAY: 250,

  // Audio quality monitoring
  MAX_LOW_AUDIO_COUNT: 3,

  // Audio configuration
  APP_ID: 'b692145dadfd4f2b9bd3c0e9e5ecaab8',
  AUDIO_PROFILE: 'high_quality',
  MAX_VOLUME: 1000,

  // VAD configuration
  VAD_CONFIDENCE_THRESHOLD: 0.1,
  VAD_SPEAKING_HISTORY: 2,
  VAD_SPEAKING_RATIO_THRESHOLD: 0.15,

  // Agora VAD configuration
  MUSIC_THRESHOLD: 0.7,
  MIN_PITCH_FREQ: 50,
  MAX_PITCH_FREQ: 400,
} as const;

export const VAD_CONFIG = {
  POSITIVE_SPEECH_THRESHOLD: 0.1,
  NEGATIVE_SPEECH_THRESHOLD: 0.05,
  REDEMPTION_FRAMES: 2,
  PRE_SPEECH_PAD_FRAMES: 1,
  MIN_SPEECH_FRAMES: 1,
  FRAME_SAMPLES: 512,
} as const;
